wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1670267652.883376
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.8.15
      5: 0.13.5
      8:
      - 1
      - 3
      - 5
acc:
  desc: null
  value: 0.7325000166893005
acti_fun:
  desc: null
  value: sigmoid
architecture:
  desc: null
  value: OneHiddenLayer
batch_size:
  desc: null
  value: 150
dataset:
  desc: null
  value: 2021-22_traditional
epochs:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 0.001
loss:
  desc: null
  value: 0.6558829545974731
num_neurons:
  desc: null
  value: 10
val_acc:
  desc: null
  value: 0.6800000071525574
val_loss:
  desc: null
  value: 0.6694563031196594
