wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1669292305.777732
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.9.13
      5: 0.13.2
      8:
      - 1
      - 3
      - 5
acc:
  desc: null
  value: 0.9893151717185974
acti_fun:
  desc: null
  value: relu
architecture:
  desc: null
  value: OneHiddenLayer
batch_size:
  desc: null
  value: 150
dataset:
  desc: null
  value: 2019-20_advance
epochs:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 0.0001
loss:
  desc: null
  value: 0.10749512224942445
num_neurons:
  desc: null
  value: 200
val_acc:
  desc: null
  value: 0.708700007790327
val_loss:
  desc: null
  value: 0.5393975840210915
