wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1669287723.597081
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.9.13
      5: 0.13.2
      8:
      - 1
      - 3
      - 5
acc:
  desc: null
  value: 0.977505923640728
acti_fun:
  desc: null
  value: relu
architecture:
  desc: null
  value: OneHiddenLayerDropout
batch_size:
  desc: null
  value: 200
dataset:
  desc: null
  value: 2018-19_advance
epochs:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 0.001
loss:
  desc: null
  value: 0.06124678832888603
num_neurons:
  desc: null
  value: 50
p-dropout:
  desc: null
  value: 0.5
val_acc:
  desc: null
  value: 0.6798440065443516
val_loss:
  desc: null
  value: 1.589766433620453
