wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1669218677.496916
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.9.13
      5: 0.13.2
      8:
      - 1
      - 3
      - 5
acc:
  desc: null
  value: 0.8577496243655681
acti_fun:
  desc: null
  value: sigmoid
architecture:
  desc: null
  value: OneHiddenLayerL2
batch_size:
  desc: null
  value: 200
dataset:
  desc: null
  value: 2018-19_traditional
epochs:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 0.0001
loss:
  desc: null
  value: 0.37564503204226496
num_neurons:
  desc: null
  value: 50
pl2:
  desc: null
  value: 0.001
val_acc:
  desc: null
  value: 0.5922640112757683
val_loss:
  desc: null
  value: 0.8888363719463348
