wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1670267686.349901
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.8.15
      5: 0.13.5
      8:
      - 1
      - 3
      - 5
acc:
  desc: null
  value: 0.7648333311080933
acti_fun:
  desc: null
  value: relu
architecture:
  desc: null
  value: OneHiddenLayer
batch_size:
  desc: null
  value: 150
dataset:
  desc: null
  value: 2021-22_traditional
epochs:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 0.0001
loss:
  desc: null
  value: 0.6032552719116211
num_neurons:
  desc: null
  value: 150
val_acc:
  desc: null
  value: 0.6380000114440918
val_loss:
  desc: null
  value: 0.6969524621963501
