wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1670331727.240177
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.8.15
      5: 0.13.5
      8:
      - 1
      - 3
      - 5
acc:
  desc: null
  value: 0.8024999499320984
acti_fun:
  desc: null
  value: relu
architecture:
  desc: null
  value: OneHiddenLayerL2
batch_size:
  desc: null
  value: 150
dataset:
  desc: null
  value: 2019-20_traditional
epochs:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 0.01
loss:
  desc: null
  value: 0.561254620552063
num_neurons:
  desc: null
  value: 50
val_acc:
  desc: null
  value: 0.6599999666213989
val_loss:
  desc: null
  value: 1.6626274585723877
